#!/usr/bin/env ansible-playbook
- name: Install OpenVPN Server packages 
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items: 
     - openvpn
     - easy-rsa
  tags: install
     
- name: Set ip forwarding in the sysctl file and reload if necessary
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes
  tags: configure 

- name: Enable IPv4 traffic forwarding - (/proc/sys/net/ipv4/ip_forward)
  command: echo 1 > /proc/sys/net/ipv4/ip_forward
  tags: configure

- name: Copy easy-rsa files to OpenVPN directory
  synchronize: mode=pull src=/usr/share/easy-rsa dest=/etc/openvpn/
  tags: configure

- name: Copy server.conf file to OpenVPN directory
  template: src=server.conf.j2 dest={{ openvpn_path }}/server.conf
  tags: configure

- name: Create directory 
  file: path={{ openvpn_rsa_ca_dir }} state=directory
  tags: configure

- name: Copy easy-rsa vars file
  template: src=vars.j2 dest={{ openvpn_easy_rsa_dir }}/vars  
  tags: easy_rsa
- name: Create DH key
  command: openssl dhparam -out {{ openvpn_path }}/dh2048.pem 2048

- name: Clean All
  shell: ". ./vars; ./clean-all > /dev/null"
  args:
    chdir: "{{ openvpn_easy_rsa_dir }}"
  tags: easy_rsa

- name: Build CA
  shell: ". ./vars; ./pkitool --initca >/dev/null"
  args:
    chdir: "{{ openvpn_easy_rsa_dir }}"
    creates: "{{ openvpn_rsa_ca_dir }}/ca.key"
  tags: easy_rsa

- name: Generate server certificate and key
  shell: ". ./vars; ./pkitool --server {{ openvpn_server }} >/dev/null"
  args:
    chdir: "{{ openvpn_easy_rsa_dir }}"
    creates: "{{ openvpn_rsa_ca_dir }}/{{ openvpn_server }}.key"
  tags: easy_rsa

- name: Copy Server ca.crt to the main directory
  copy: src={{ openvpn_rsa_ca_dir }}/ca.crt dest={{ openvpn_path }}
  tags: easy_rsa

- name: Copy Server certificates to the main directory
  copy: src={{ openvpn_rsa_ca_dir }}/{{ openvpn_server }}.crt dest={{ openvpn_path }}

- name: Copy Server certificates to the main directory
  copy: src={{ openvpn_rsa_ca_dir }}/{{ openvpn_server }}.key dest={{ openvpn_path }}
  tags: easy_rsa

- name: Start OpenVPN server
  service: name=openvpn state=started

- name: Generate client certificates and keys
  shell: ". ./vars; ./pkitool {{ item }} >/dev/null"
  args:
    chdir: "{{ openvpn_easy_rsa_dir }}"
    creates: "{{ openvpn_rsa_ca_dir }}/{{ item}}.key"
  with_items: "{{ openvpn_clients }}"  
  tags: easy_rsa

  
