#!/usr/bin/env ansible-playbook
- name: Install OpenVPN Server packages 
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items: 
     - openvpn
     - easy-rsa
     
- name: Set ip forwarding in the sysctl file and reload if necessary
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Enable IPv4 traffic forwarding - (/proc/sys/net/ipv4/ip_forward)
  command: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Copy easy-rsa files to OpenVPN directory
  synchronize: mode=pull src=/usr/share/easy-rsa dest=/etc/openvpn/

- name: Create directory 
  file: path=/etc/openvpn/easy-rsa/keys state=directory

- name: Copy easy-rsa vars file
  template: src=vars.j2 dest=/etc/openvpn/easy-rsa/vars  

- name: Create DH key
  command: openssl dhparam -out /etc/openvpn/dh2048.pem 2048

#- name: Create CA


#- name: Generate the RSA keys
#  command: openssl genrsa -out {{ item }}.key {{ openvpn_key_size }} creates={{ item }}.key
##           chdir={{ openvpn_path }}
#  with_items:
#    - ca
#    - server