#!/usr/bin/env ansible-playbook
- name: Install OpenVPN Server packages 
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items: 
     - openvpn
     - easy-rsa
     
- name: Set ip forwarding in the sysctl file and reload if necessary
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Enable IPv4 traffic forwarding - (/proc/sys/net/ipv4/ip_forward)
  command: echo 1 > /proc/sys/net/ipv4/ip_forward

- name: Generate the RSA keys
  command: openssl genrsa -out {{ item }}.key {{ openvpn_key_size }} creates={{ item }}.key
           chdir={{ openvpn_path }}
  with_items:
    - ca
    - server